{{- range .Values.apps }}
{{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    path: {{ .repo.path }}
    repoURL: {{ .repo.url }}
    targetRevision: {{ .repo.ref }}
    helm:
      valueFiles:
        - {{ .helm.valuesFile }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  {{- if .sync }}
  syncPolicy:
    automated:
      prune: {{ .sync.prune }}
      selfHeal: {{ .sync.selfHeal }}
    syncOptions:
      - CreateNamespace=false
  {{- else }}
  syncPolicy: {}
  {{- end }}
{{- end }}
{{- end }}
