FROM python:3.8-slim-buster

WORKDIR /app/

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN useradd -U -s /bin/false app
USER app

COPY shared /app/shared
COPY scheduler /app/scheduler
Copy tests /app/tests

EXPOSE 8103

CMD ["uvicorn", "tests.dummy_ptr:app", "--host", "0.0.0.0", "--port", "8103"]
