name: scheduler

replicaCount: 1
revisionHistoryLimit: 1
rolloutStaregy: RollingUpdate

image:
  repository: docker-registry.lab.nordigy.ru/ptsd/scheduler
  tag: latest
  pullPolicy: Always

service:
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
    - host: test  # CHANGE ME
      paths:
        - path: /
          port: 8000

servicemonitor:
  enabled: true
  promOperatorSelector: default
  path: /metrics
  port: http

resources:
  limits:
    cpu: "0.5"
    memory: "512Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

envVariables:
  - name: 123  # CHANGE_ME
    value: test
