---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: {{ .Values.rolloutStaregy }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.envVariables }}
          env:
            {{- range .Values.envVariables }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
      imagePullSecrets:
        - name: docker-registry
      {{- if .Values.config }}
      volumes:
        name: {{ .Values.name }}-config
        configMap:
          name: {{ .Values.name }}-config
          items:
            - key: {{ .Values.config.fileName }}
              path: {{ .Values.config.path }}/{{ .Values.config.fileName }}
      {{- end }}
