---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    {{- if .Values.servicemonitor.enabled }}
    prometheus: {{ .Values.servicemonitor.promOperatorSelector }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
